# Generated by Django 2.2.16 on 2021-12-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='genre',
            table='genre',
        ),
        migrations.AlterModelTable(
            name='genretitle',
            table='genre_title',
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
        migrations.AlterModelTable(
            name='title',
            table='titles',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
